### ISSUE TITLE
Attached Schemas not updated on client side

### ISSUE THREAD

**Issue by artjomg** [Yodata/meteor-json-simple-schema#12]
Hi,

Great package!

I think this question is more related to Collection2 package. But maybe you know what I can do to update the merged Schema on the client. Here is the issue.

Using your package I can successfully update my SimpleSchema on the server side.
        Schemas.ArticlesProfiled = jsonSchema.toSimpleSchema()
        Articles.attachSchema(Schemas.ArticlesProfiled);
Looking at the Schema gives me the merged Version:

console.log(Articles._c2._simpleSchema._schemaKeys);

But on the client the new Properties are not updated. So auto form and tabular table are not showing the new Information.

**Comment by bshamblen** [comment]
@artjomg Would you mind including the code that shows how you're loading the JSON schema document? As long as the JSON schema data is there, it should work the same on both the client and server.

**Comment by artjomg** [comment]
@bshamblen 

First of all I have a static file in both>collections>articlesSchema.js

```
Articles = new Mongo.Collection("articles");
Schemas.Articles = new SimpleSchema({
  name:{
    type: String,
    max: 255,
    optional: false
  },
  price:{
      type: Number,
      decimal: true,
      optional: true
    }
});
Articles.attachSchema(Schemas.Articles);

Articles.allow({
insert: function () { return true; },
update: function () { return true; },
remove: function () { return true; }
});

```

additionally I have a collection called Profiles where I store some additional schema in JSON form

```

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "properties": {
    "address": {
      "id": "address",
      "type": "object",
      "properties": {
        "streetAddress": {
          "id": "streetAddress",
          "type": "string"
        },
        "city": {
          "id": "city",
          "type": "string"
        }
      }
    },
    "phoneNumber": {
      "id": "phoneNumber",
      "type": "array",
      "items": {
        "id": "0",
        "type": "object",
        "properties": {
          "location": {
            "id": "location",
            "type": "string"
          },
          "code": {
            "id": "code",
            "type": "integer"
          }
        }
      }
    }
  }
}

```

I have  a startup method in >server>init.js

```
Meteor.startup(function () {


function loadArticleProflie() {

      var profile = Profiles.findOne({name:"CUSTOM"});
      var jsonSchema = new JSONSchema(JSON.parse(profile.articleSchema));
      Schemas.ArticlesProfiled = jsonSchema.toSimpleSchema();
      Articles.attachSchema(Schemas.ArticlesProfiled);
      console.log(Articles._c2._simpleSchema._schemaKeys);

    }

    loadArticleProflie();
});

```

This guides to a successful Articles C2 Schema update, but only server side.
However I don't understand what I have to do to update the Schema to all clients.
When I use quick form/ tabular table on client side I have to add the new fields via extraFields().

```
ArticlesTable.ArticlesList.extraFields = extraFields();

function extraFields() {
    var fields = [];
    var schemaKeys = Articles._c2._simpleSchema._schemaKeys;
    for( i=0; i<schemaKeys.length; i++ ){
            if (schemaKeys[i].indexOf("$") === -1){
                    fields.push(schemaKeys[i]);
            }
    }
    return fields;
}

//The table is defined previously

ArticlesTable.ArticlesList = new Tabular.Table({
  name: "List of Articles",
  collection: Articles,
  autoWidth: false,
  columns: [
    {data: "name", title: "Article", class: "col-lg-9 cursor-pointer"},
    {title:"",tmpl: Meteor.isClient && Template.ArticlesActionBtns, class: "col-xs-3 text-center"}
  ],
  extraFields: extraFields()
});


```

however I have to call the schema attach method manually in advance on the client side too via a method call updateArticleSchema:

```

Meteor.methods({

    'updateArticleSchema': function(profile){

        var jsonSchema = new JSONSchema(JSON.parse(profile.articleSchema))
            Schemas.ArticlesProfiled = jsonSchema.toSimpleSchema();
        Articles.attachSchema(Schemas.ArticlesProfiled);
        console.log(Articles._c2._simpleSchema._schemaKeys);

    }

});

```

only after this explicit call the new Fields appear in the quickForm.

I would like to have this reactive.

The Idea is that different customers can define additional fields in the backend, which schould automatically propagate to all clients reactive.

Hope you understand this. 

The main issue I have at the moment, is that the fields appear in the quickForm and are even stored in the backend. But are not shown in the update quickForm :(

**Comment by bshamblen** [comment]
Unfortunately this approach would probably result in random, unexpected validation errors. 
1. Lets assume **User A** visits the site and clicks on a link to open your `Article` editor. You load the custom schema on the client and server, AutoForm loads the form correctly, and the user starts editing their article. 
2. Now, **User B** visits the site and selects a different `Article` template. You would then update the `Article` schema on the server to work for **User B's** template, their form would load and they would start entering data. 
3. Now, **User A** tries to submit their form, but gets an error, because the schema for the `Article` collection has changed on the server since their form was rendered. 

A better approach might be to set the `extraFields` property to `blackbox: true` on the server side, and just let anything get submitted. On the client side, instead of loading the schema keys from the `Articles.c2._simpleSchema._schemaKeys` object, you could build the custom schema on the fly and pass it to `Tabular.Table` or `AutoForm`.

I'm not familiar with the `Tabular.Table` package, but with `AutoForm` you can specify a `schema` instead of a `collection` and validation will still work. You just need to use the `AutoForm.hooks` feature to insert or update the document manually, using the validated doc. If you use `blackbox` on the server, you won't have any issue with varying schemas on the client side.

**example**

```
{{>quickForm id='customForm' schema=customSchema type='normal' doc=getDoc}}
```

`customSchema` in this case is a schema that was generated dynamically in the Iron router `data` function, and `getDoc` is a template helper function to load the document that's being edited or inserted.

Hopefully I didn't misunderstand what you're trying to accomplish. Let me know if you have any more questions. I don't think this is an issue with this package, but I'm happy to help you find a solution.

**Comment by artjomg** [comment]
@bshamblen Thanks for the detailed review. You got the points exactly right, with the concurrent validation issue! Thanks also for explaining the balckbox validation alternative too.
There is one minor point I want to adjust is, that the additional fields configuration should happen only once on start and would require restart of the app, which is fine in our scenario. It is a multi tenant approach and each customer would configure/adjust their own properties to a basic scheme. From time to time.

Finally I figured out that the main issue is caused by a missing subscription. Now the cycle is working fine. The only thing I have to figure out is how to merge the Schemas static file + fromJSONSchema on start up, which is probably a general meteor thing and is not related to your package.
So it is up to you to close this issue. Appreciate your support. Thanks.

One last Question is the ref attribute feature already merged or not?

Thanks,
ArtjomG

**Comment by bshamblen** [comment]
Glad to hear you got it to work. The ref attribute works for internally referenced definitions, in the same JSON schema doc, but not for external urls yet. I plan to work on it in the future, but just haven't had the time recently.

**Comment by artjomg** [comment]
Hi,

one more Thing.
Is it possible to provide for example additional properties such as auto form types?

 "bussines": {
      "id": "business",
      "type": "boolean",
     	"autoform": {
		"type": "select-checkbox-icheck"
	}
